name: Market Mood Index Bot

on:
  schedule:
    # Runs at 9:50 AM IST (4:20 AM UTC) on weekdays
    - cron: '20 4 * * 1-5'
  workflow_dispatch: # Allows manual triggering

jobs:
  send-market-mood:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run Market Mood Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python market_mood_bot.py
